# Generated by Django 5.0.7 on 2024-07-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('age', models.IntegerField(null=True)),
                ('corecourse', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('dateofjoin', models.DateField(null=True)),
            ],
        ),
    ]
