# Generated by Django 5.0.7 on 2024-07-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='images',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
